# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0003_auto_20170430_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='emailaddress',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
