# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0004_auto_20170430_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
