# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0006_auto_20170501_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
