# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0007_auto_20170501_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='provided_skill',
            unique_together=set([('owner', 'skill')]),
        ),
        migrations.AlterUniqueTogether(
            name='required_skill',
            unique_together=set([('owner', 'skill')]),
        ),
    ]
