# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0008_auto_20170501_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='provided_skill',
            name='skill_string',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
