# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0009_provided_skill_skill_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='required_skill',
            name='skill_string',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
