# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0010_required_skill_skill_string'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_string', models.CharField(max_length=54, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.User_Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('city', 'state')]),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondchances.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='user_location',
            unique_together=set([('owner', 'location')]),
        ),
    ]
