# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secondchances', '0011_auto_20170502_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provided_Needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_string', models.CharField(max_length=25, null=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.Needs')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='secondchances.Location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='User_Needs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('need_string', models.CharField(max_length=25, null=True)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.Needs')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.User_Profile')),
            ],
        ),
        migrations.AddField(
            model_name='provided_needs',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondchances.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='provided_needs',
            unique_together=set([('owner', 'need')]),
        ),
    ]
